call pyuic4 mainUi.ui -o mainUi.py
call pyuic4 designer\main_tab_pageUi.ui -o designer\main_tab_pageUi.py
call pyuic4 designer\side_barUi.ui -o designer\side_barUi.py
call pyuic4 tab_featuresUi.ui -o tab_featuresUi.py
call pyuic4 tab_objectsUi.ui -o tab_objectsUi.py
call pyuic4 tab_regionsUi.ui -o tab_regionsUi.py
call pyuic4 tab_serialUi.ui -o tab_serialUi.py
call pyuic4 statusBarUi.ui -o statusBarUi.py
call pyuic4 arduino_indicator_widget.ui -o arduino_indicator_widget.py
call pyrcc4 icons.qrc -o icons_rc.py