# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created: Sat Jan 12 19:07:49 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(681, 387)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_video = QtGui.QHBoxLayout()
        self.frame_video.setSpacing(0)
        self.frame_video.setObjectName(_fromUtf8("frame_video"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.frame_video.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_video.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.frame_video)
        self.frame_parameters = QtGui.QHBoxLayout()
        self.frame_parameters.setObjectName(_fromUtf8("frame_parameters"))
        self.tab_phys = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_phys.sizePolicy().hasHeightForWidth())
        self.tab_phys.setSizePolicy(sizePolicy)
        self.tab_phys.setObjectName(_fromUtf8("tab_phys"))
        self.widget_settings = QtGui.QWidget()
        self.widget_settings.setObjectName(_fromUtf8("widget_settings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_settings)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(self.widget_settings)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.widget_settings)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.toolButton = QtGui.QToolButton(self.widget_settings)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_2.addWidget(self.toolButton, 0, 0, 1, 1)
        self.tab_phys.addTab(self.widget_settings, _fromUtf8(""))
        self.widget_features = QtGui.QWidget()
        self.widget_features.setObjectName(_fromUtf8("widget_features"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_features)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tab_features = QtGui.QTabWidget(self.widget_features)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_features.sizePolicy().hasHeightForWidth())
        self.tab_features.setSizePolicy(sizePolicy)
        self.tab_features.setMinimumSize(QtCore.QSize(320, 300))
        self.tab_features.setTabPosition(QtGui.QTabWidget.East)
        self.tab_features.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_features.setElideMode(QtCore.Qt.ElideNone)
        self.tab_features.setObjectName(_fromUtf8("tab_features"))
        self.tab_features_RLED = QtGui.QWidget()
        self.tab_features_RLED.setObjectName(_fromUtf8("tab_features_RLED"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_features_RLED)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolBox = QtGui.QToolBox(self.tab_features_RLED)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 281, 216))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));"))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 4, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.page)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.page)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_9.addWidget(self.spinBox_5, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.page)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_9.addWidget(self.spinBox_4, 3, 2, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.page)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_9.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.page)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_9.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_9.addWidget(self.spinBox, 1, 2, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.page)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_9.addWidget(self.spinBox_6, 2, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_9.addWidget(self.pushButton_10, 4, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.page)
        self.comboBox.setEditable(True)
        self.comboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox, 1, 0, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.tab_features_buttons = QtGui.QWidget()
        self.tab_features_buttons.setGeometry(QtCore.QRect(0, 0, 211, 216))
        self.tab_features_buttons.setObjectName(_fromUtf8("tab_features_buttons"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_features_buttons)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_7.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_7.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_7.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_7.addWidget(self.pushButton_5, 1, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 1)
        self.toolBox.addItem(self.tab_features_buttons, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.toolBox, 1, 0, 1, 1)
        self.tab_features.addTab(self.tab_features_RLED, _fromUtf8(""))
        self.tab_features_GLED = QtGui.QWidget()
        self.tab_features_GLED.setObjectName(_fromUtf8("tab_features_GLED"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_features_GLED)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tab_features.addTab(self.tab_features_GLED, _fromUtf8(""))
        self.tab_features_BLED = QtGui.QWidget()
        self.tab_features_BLED.setObjectName(_fromUtf8("tab_features_BLED"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_features_BLED)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tab_features.addTab(self.tab_features_BLED, _fromUtf8(""))
        self.tab_features_newTab = QtGui.QWidget()
        self.tab_features_newTab.setObjectName(_fromUtf8("tab_features_newTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_features_newTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_features_newTab)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.tab_features.addTab(self.tab_features_newTab, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tab_features)
        self.tab_phys.addTab(self.widget_features, _fromUtf8(""))
        self.widget_objects = QtGui.QWidget()
        self.widget_objects.setObjectName(_fromUtf8("widget_objects"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_objects)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setMargin(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tab_objects = QtGui.QTabWidget(self.widget_objects)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_objects.sizePolicy().hasHeightForWidth())
        self.tab_objects.setSizePolicy(sizePolicy)
        self.tab_objects.setMinimumSize(QtCore.QSize(250, 200))
        self.tab_objects.setTabPosition(QtGui.QTabWidget.East)
        self.tab_objects.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_objects.setElideMode(QtCore.Qt.ElideNone)
        self.tab_objects.setObjectName(_fromUtf8("tab_objects"))
        self.tab_objects_sync = QtGui.QWidget()
        self.tab_objects_sync.setObjectName(_fromUtf8("tab_objects_sync"))
        self.gridLayout = QtGui.QGridLayout(self.tab_objects_sync)
        self.gridLayout.setMargin(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolBox_2 = QtGui.QToolBox(self.tab_objects_sync)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 209, 223))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalSlider = QtGui.QSlider(self.page_3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_5.addWidget(self.horizontalSlider, 0, 0, 1, 1)
        self.horizontalSlider_2 = QtGui.QSlider(self.page_3)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.gridLayout_5.addWidget(self.horizontalSlider_2, 1, 0, 1, 1)
        self.horizontalSlider_3 = QtGui.QSlider(self.page_3)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.gridLayout_5.addWidget(self.horizontalSlider_3, 2, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.page_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_5.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.toolBox_2.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 194, 78))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton = QtGui.QPushButton(self.page_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 2, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.page_4)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_4.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_4)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_4.addWidget(self.pushButton_2, 3, 0, 1, 2)
        self.toolBox_2.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolBox_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 2)
        self.tab_objects.addTab(self.tab_objects_sync, _fromUtf8(""))
        self.tab_object_subject = QtGui.QWidget()
        self.tab_object_subject.setObjectName(_fromUtf8("tab_object_subject"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_object_subject)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButton = QtGui.QRadioButton(self.tab_object_subject)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.tab_objects.addTab(self.tab_object_subject, _fromUtf8(""))
        self.tab_object_newTab = QtGui.QWidget()
        self.tab_object_newTab.setObjectName(_fromUtf8("tab_object_newTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_object_newTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_object_newTab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.tab_objects.addTab(self.tab_object_newTab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tab_objects)
        self.tab_phys.addTab(self.widget_objects, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tab_phys.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tab_phys.addTab(self.tab, _fromUtf8(""))
        self.frame_parameters.addWidget(self.tab_phys)
        self.horizontalLayout_2.addLayout(self.frame_parameters)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Open = QtGui.QMenu(self.menu_File)
        self.menu_Open.setObjectName(_fromUtf8("menu_Open"))
        self.menu_Save = QtGui.QMenu(self.menu_File)
        self.menu_Save.setObjectName(_fromUtf8("menu_Save"))
        self.menuLoad = QtGui.QMenu(self.menu_File)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionDevice = QtGui.QAction(MainWindow)
        self.actionDevice.setObjectName(_fromUtf8("actionDevice"))
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.action_Parameters = QtGui.QAction(MainWindow)
        self.action_Parameters.setObjectName(_fromUtf8("action_Parameters"))
        self.action_Transcode_Video = QtGui.QAction(MainWindow)
        self.action_Transcode_Video.setObjectName(_fromUtf8("action_Transcode_Video"))
        self.actionParameters = QtGui.QAction(MainWindow)
        self.actionParameters.setObjectName(_fromUtf8("actionParameters"))
        self.menu_Open.addAction(self.actionFile)
        self.menu_Open.addAction(self.actionDevice)
        self.menu_Save.addAction(self.action_Transcode_Video)
        self.menu_Save.addAction(self.actionParameters)
        self.menuLoad.addAction(self.action_Parameters)
        self.menu_File.addAction(self.menu_Open.menuAction())
        self.menu_File.addAction(self.menuLoad.menuAction())
        self.menu_File.addAction(self.menu_Save.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_phys.setCurrentIndex(1)
        self.tab_features.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)
        self.tab_objects.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spotter", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_phys.setTabText(self.tab_phys.indexOf(self.widget_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Tracking Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Val", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setToolTip(QtGui.QApplication.translate("MainWindow", "Pick thresholds from image by dragging frame around the spot of interest", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setStatusTip(QtGui.QApplication.translate("MainWindow", "Pick rage from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "redLED", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "greenLED", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "blueLED", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), QtGui.QApplication.translate("MainWindow", "Restrictions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Clone", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab_features_buttons), QtGui.QApplication.translate("MainWindow", "In/Out", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_features.setTabText(self.tab_features.indexOf(self.tab_features_RLED), QtGui.QApplication.translate("MainWindow", "redLED", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_features.setTabText(self.tab_features.indexOf(self.tab_features_GLED), QtGui.QApplication.translate("MainWindow", "greenLED", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_features.setTabText(self.tab_features.indexOf(self.tab_features_BLED), QtGui.QApplication.translate("MainWindow", "redLED", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_features.setTabText(self.tab_features.indexOf(self.tab_features_newTab), QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_phys.setTabText(self.tab_phys.indexOf(self.widget_features), QtGui.QApplication.translate("MainWindow", "Features", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_objects.setTabText(self.tab_objects.indexOf(self.tab_objects_sync), QtGui.QApplication.translate("MainWindow", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_objects.setTabText(self.tab_objects.indexOf(self.tab_object_subject), QtGui.QApplication.translate("MainWindow", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_objects.setTabText(self.tab_objects.indexOf(self.tab_object_newTab), QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_phys.setTabText(self.tab_phys.indexOf(self.widget_objects), QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_phys.setTabText(self.tab_phys.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "ROIs", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_phys.setTabText(self.tab_phys.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "SerialOut", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Open.setTitle(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Save.setTitle(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevice.setText(QtGui.QApplication.translate("MainWindow", "&Device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setText(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Transcode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Parameters.setText(QtGui.QApplication.translate("MainWindow", "&Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Transcode_Video.setText(QtGui.QApplication.translate("MainWindow", "&Transcode Video", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParameters.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))

