# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created: Thu Jan 17 21:58:59 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(681, 387)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon64.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_video = QtGui.QHBoxLayout()
        self.frame_video.setSpacing(0)
        self.frame_video.setObjectName(_fromUtf8("frame_video"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.frame_video.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_video.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.frame_video)
        self.frame_parameters = QtGui.QHBoxLayout()
        self.frame_parameters.setObjectName(_fromUtf8("frame_parameters"))
        self.tab_parameters = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_parameters.sizePolicy().hasHeightForWidth())
        self.tab_parameters.setSizePolicy(sizePolicy)
        self.tab_parameters.setMinimumSize(QtCore.QSize(320, 300))
        self.tab_parameters.setTabPosition(QtGui.QTabWidget.North)
        self.tab_parameters.setObjectName(_fromUtf8("tab_parameters"))
        self.widget_settings = QtGui.QWidget()
        self.widget_settings.setObjectName(_fromUtf8("widget_settings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_settings)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.combo_templates = QtGui.QComboBox(self.widget_settings)
        self.combo_templates.setObjectName(_fromUtf8("combo_templates"))
        self.horizontalLayout_3.addWidget(self.combo_templates)
        self.btn_load_template = QtGui.QPushButton(self.widget_settings)
        self.btn_load_template.setObjectName(_fromUtf8("btn_load_template"))
        self.horizontalLayout_3.addWidget(self.btn_load_template)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tab_parameters.addTab(self.widget_settings, _fromUtf8(""))
        self.widget_features = QtGui.QWidget()
        self.widget_features.setObjectName(_fromUtf8("widget_features"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_features)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tab_features = QtGui.QTabWidget(self.widget_features)
        self.tab_features.setTabPosition(QtGui.QTabWidget.East)
        self.tab_features.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_features.setObjectName(_fromUtf8("tab_features"))
        self.tab_features_newTab = QtGui.QWidget()
        self.tab_features_newTab.setObjectName(_fromUtf8("tab_features_newTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_features_newTab)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btn_new_feature_tab = QtGui.QPushButton(self.tab_features_newTab)
        self.btn_new_feature_tab.setObjectName(_fromUtf8("btn_new_feature_tab"))
        self.verticalLayout_2.addWidget(self.btn_new_feature_tab)
        self.btn_feature_template = QtGui.QPushButton(self.tab_features_newTab)
        self.btn_feature_template.setObjectName(_fromUtf8("btn_feature_template"))
        self.verticalLayout_2.addWidget(self.btn_feature_template)
        self.tab_features.addTab(self.tab_features_newTab, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tab_features)
        self.tab_parameters.addTab(self.widget_features, _fromUtf8(""))
        self.widget_objects = QtGui.QWidget()
        self.widget_objects.setObjectName(_fromUtf8("widget_objects"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_objects)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tab_objects = QtGui.QTabWidget(self.widget_objects)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_objects.sizePolicy().hasHeightForWidth())
        self.tab_objects.setSizePolicy(sizePolicy)
        self.tab_objects.setMinimumSize(QtCore.QSize(250, 200))
        self.tab_objects.setTabPosition(QtGui.QTabWidget.East)
        self.tab_objects.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_objects.setObjectName(_fromUtf8("tab_objects"))
        self.tab_object_newTab = QtGui.QWidget()
        self.tab_object_newTab.setObjectName(_fromUtf8("tab_object_newTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_object_newTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btn_new_object_tab = QtGui.QPushButton(self.tab_object_newTab)
        self.btn_new_object_tab.setObjectName(_fromUtf8("btn_new_object_tab"))
        self.verticalLayout.addWidget(self.btn_new_object_tab)
        self.btn_object_template = QtGui.QPushButton(self.tab_object_newTab)
        self.btn_object_template.setObjectName(_fromUtf8("btn_object_template"))
        self.verticalLayout.addWidget(self.btn_object_template)
        self.tab_objects.addTab(self.tab_object_newTab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tab_objects)
        self.tab_parameters.addTab(self.widget_objects, _fromUtf8(""))
        self.widget_regions = QtGui.QWidget()
        self.widget_regions.setObjectName(_fromUtf8("widget_regions"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_regions)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tab_regions = QtGui.QTabWidget(self.widget_regions)
        self.tab_regions.setTabPosition(QtGui.QTabWidget.East)
        self.tab_regions.setObjectName(_fromUtf8("tab_regions"))
        self.tab_regions_newTab = QtGui.QWidget()
        self.tab_regions_newTab.setObjectName(_fromUtf8("tab_regions_newTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_regions_newTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btn_new_region_tab = QtGui.QPushButton(self.tab_regions_newTab)
        self.btn_new_region_tab.setObjectName(_fromUtf8("btn_new_region_tab"))
        self.verticalLayout_3.addWidget(self.btn_new_region_tab)
        self.btn_region_template = QtGui.QPushButton(self.tab_regions_newTab)
        self.btn_region_template.setObjectName(_fromUtf8("btn_region_template"))
        self.verticalLayout_3.addWidget(self.btn_region_template)
        self.tab_regions.addTab(self.tab_regions_newTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tab_regions)
        self.tab_parameters.addTab(self.widget_regions, _fromUtf8(""))
        self.widget_serial = QtGui.QWidget()
        self.widget_serial.setObjectName(_fromUtf8("widget_serial"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_serial)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tab_serial_2 = QtGui.QTabWidget(self.widget_serial)
        self.tab_serial_2.setTabPosition(QtGui.QTabWidget.East)
        self.tab_serial_2.setObjectName(_fromUtf8("tab_serial_2"))
        self.tab_serial_arduino = QtGui.QWidget()
        self.tab_serial_arduino.setObjectName(_fromUtf8("tab_serial_arduino"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_serial_arduino)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tab_serial_2.addTab(self.tab_serial_arduino, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tab_serial_2)
        self.tab_parameters.addTab(self.widget_serial, _fromUtf8(""))
        self.frame_parameters.addWidget(self.tab_parameters)
        self.horizontalLayout_2.addLayout(self.frame_parameters)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Open = QtGui.QMenu(self.menu_File)
        self.menu_Open.setObjectName(_fromUtf8("menu_Open"))
        self.menu_Save = QtGui.QMenu(self.menu_File)
        self.menu_Save.setObjectName(_fromUtf8("menu_Save"))
        self.menuLoad = QtGui.QMenu(self.menu_File)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionDevice = QtGui.QAction(MainWindow)
        self.actionDevice.setObjectName(_fromUtf8("actionDevice"))
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.action_Parameters = QtGui.QAction(MainWindow)
        self.action_Parameters.setObjectName(_fromUtf8("action_Parameters"))
        self.action_Transcode_Video = QtGui.QAction(MainWindow)
        self.action_Transcode_Video.setObjectName(_fromUtf8("action_Transcode_Video"))
        self.actionParameters = QtGui.QAction(MainWindow)
        self.actionParameters.setObjectName(_fromUtf8("actionParameters"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_Open.addAction(self.actionFile)
        self.menu_Open.addAction(self.actionDevice)
        self.menu_Save.addAction(self.action_Transcode_Video)
        self.menu_Save.addAction(self.actionParameters)
        self.menuLoad.addAction(self.action_Parameters)
        self.menu_File.addAction(self.menu_Open.menuAction())
        self.menu_File.addAction(self.menuLoad.menuAction())
        self.menu_File.addAction(self.menu_Save.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_parameters.setCurrentIndex(0)
        self.tab_features.setCurrentIndex(0)
        self.tab_objects.setCurrentIndex(0)
        self.tab_regions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spotter", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_template.setText(QtGui.QApplication.translate("MainWindow", "Load Template", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.widget_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_feature_tab.setText(QtGui.QApplication.translate("MainWindow", "Add LED/Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_feature_template.setText(QtGui.QApplication.translate("MainWindow", "Quickload Feature template", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_features.setTabText(self.tab_features.indexOf(self.tab_features_newTab), QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.widget_features), QtGui.QApplication.translate("MainWindow", "Features", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_object_tab.setText(QtGui.QApplication.translate("MainWindow", "Add Object", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_object_template.setText(QtGui.QApplication.translate("MainWindow", "Quickload object template", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_objects.setTabText(self.tab_objects.indexOf(self.tab_object_newTab), QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.widget_objects), QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_region_tab.setText(QtGui.QApplication.translate("MainWindow", "New Region", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_region_template.setText(QtGui.QApplication.translate("MainWindow", "Quickload region template", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_regions.setTabText(self.tab_regions.indexOf(self.tab_regions_newTab), QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.widget_regions), QtGui.QApplication.translate("MainWindow", "ROIs", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_serial_2.setTabText(self.tab_serial_2.indexOf(self.tab_serial_arduino), QtGui.QApplication.translate("MainWindow", "Arduino", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.widget_serial), QtGui.QApplication.translate("MainWindow", "SerialOut", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Open.setTitle(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Save.setTitle(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevice.setText(QtGui.QApplication.translate("MainWindow", "&Device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setText(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Transcode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Parameters.setText(QtGui.QApplication.translate("MainWindow", "&Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Transcode_Video.setText(QtGui.QApplication.translate("MainWindow", "&Transcode Video", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParameters.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
