# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_objectsUi.ui'
#
# Created: Mon Jan 14 00:37:02 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_tab_objects(object):
    def setupUi(self, tab_objects):
        tab_objects.setObjectName(_fromUtf8("tab_objects"))
        tab_objects.resize(304, 326)
        self.gridLayout = QtGui.QGridLayout(tab_objects)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolBox = QtGui.QToolBox(tab_objects)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_objects_tracking = QtGui.QWidget()
        self.page_objects_tracking.setGeometry(QtCore.QRect(0, 0, 302, 249))
        self.page_objects_tracking.setObjectName(_fromUtf8("page_objects_tracking"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_objects_tracking)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.listWidget = QtGui.QListWidget(self.page_objects_tracking)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget, 3, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_objects_tracking)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.page_objects_tracking)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.combo_label = QtGui.QComboBox(self.page_objects_tracking)
        self.combo_label.setEditable(True)
        self.combo_label.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.combo_label.setObjectName(_fromUtf8("combo_label"))
        self.gridLayout_3.addWidget(self.combo_label, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lbl_y_lbl = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_y_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_y_lbl.setObjectName(_fromUtf8("lbl_y_lbl"))
        self.gridLayout_5.addWidget(self.lbl_y_lbl, 1, 0, 1, 1)
        self.lbl_xlbl = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_xlbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_xlbl.setObjectName(_fromUtf8("lbl_xlbl"))
        self.gridLayout_5.addWidget(self.lbl_xlbl, 0, 0, 1, 1)
        self.lbl_x = QtGui.QLabel(self.page_objects_tracking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_x.sizePolicy().hasHeightForWidth())
        self.lbl_x.setSizePolicy(sizePolicy)
        self.lbl_x.setMinimumSize(QtCore.QSize(32, 0))
        self.lbl_x.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lbl_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_x.setObjectName(_fromUtf8("lbl_x"))
        self.gridLayout_5.addWidget(self.lbl_x, 0, 1, 1, 1)
        self.lbl_y = QtGui.QLabel(self.page_objects_tracking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_y.sizePolicy().hasHeightForWidth())
        self.lbl_y.setSizePolicy(sizePolicy)
        self.lbl_y.setMinimumSize(QtCore.QSize(32, 0))
        self.lbl_y.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lbl_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_y.setObjectName(_fromUtf8("lbl_y"))
        self.gridLayout_5.addWidget(self.lbl_y, 1, 1, 1, 1)
        self.gridLayout_5.setColumnMinimumWidth(0, 20)
        self.gridLayout_5.setColumnMinimumWidth(1, 20)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.toolBox.addItem(self.page_objects_tracking, _fromUtf8(""))
        self.page_objects_restriction = QtGui.QWidget()
        self.page_objects_restriction.setGeometry(QtCore.QRect(0, 0, 302, 249))
        self.page_objects_restriction.setObjectName(_fromUtf8("page_objects_restriction"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_objects_restriction)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.checkBox = QtGui.QCheckBox(self.page_objects_restriction)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_8.addWidget(self.checkBox, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_objects_restriction, _fromUtf8(""))
        self.page_objects_IO = QtGui.QWidget()
        self.page_objects_IO.setGeometry(QtCore.QRect(0, 0, 302, 249))
        self.page_objects_IO.setObjectName(_fromUtf8("page_objects_IO"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_objects_IO)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_8 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_7.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_7.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_7.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_7.addWidget(self.pushButton_5, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_objects_IO, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(tab_objects)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(tab_objects)

    def retranslateUi(self, tab_objects):
        tab_objects.setWindowTitle(QtGui.QApplication.translate("tab_objects", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(True)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(QtGui.QApplication.translate("tab_objects", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listWidget.item(1)
        item.setText(QtGui.QApplication.translate("tab_objects", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listWidget.item(2)
        item.setText(QtGui.QApplication.translate("tab_objects", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(QtGui.QApplication.translate("tab_objects", "Unlink from Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("tab_objects", "Link to Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y_lbl.setText(QtGui.QApplication.translate("tab_objects", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_xlbl.setText(QtGui.QApplication.translate("tab_objects", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_x.setText(QtGui.QApplication.translate("tab_objects", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y.setText(QtGui.QApplication.translate("tab_objects", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_tracking), QtGui.QApplication.translate("tab_objects", "Tracking", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("tab_objects", "Tracking Active", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_restriction), QtGui.QApplication.translate("tab_objects", "Restrictions and Triggers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("tab_objects", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("tab_objects", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("tab_objects", "Clone", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("tab_objects", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_IO), QtGui.QApplication.translate("tab_objects", "In/Out", None, QtGui.QApplication.UnicodeUTF8))

