# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_objectsUi.ui'
#
# Created: Thu Apr 04 05:48:34 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_tab_objects(object):
    def setupUi(self, tab_objects):
        tab_objects.setObjectName(_fromUtf8("tab_objects"))
        tab_objects.resize(241, 324)
        self.gridLayout = QtGui.QGridLayout(tab_objects)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolBox = QtGui.QToolBox(tab_objects)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_objects_tracking = QtGui.QWidget()
        self.page_objects_tracking.setGeometry(QtCore.QRect(0, 0, 239, 259))
        self.page_objects_tracking.setObjectName(_fromUtf8("page_objects_tracking"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_objects_tracking)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lbl_speed = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_speed.setObjectName(_fromUtf8("lbl_speed"))
        self.gridLayout_5.addWidget(self.lbl_speed, 4, 5, 1, 1)
        self.lbl_xlbl = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_xlbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_xlbl.setObjectName(_fromUtf8("lbl_xlbl"))
        self.gridLayout_5.addWidget(self.lbl_xlbl, 2, 4, 1, 1)
        self.lbl_y = QtGui.QLabel(self.page_objects_tracking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_y.sizePolicy().hasHeightForWidth())
        self.lbl_y.setSizePolicy(sizePolicy)
        self.lbl_y.setMinimumSize(QtCore.QSize(32, 0))
        self.lbl_y.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lbl_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_y.setObjectName(_fromUtf8("lbl_y"))
        self.gridLayout_5.addWidget(self.lbl_y, 3, 5, 1, 1)
        self.ckb_track = QtGui.QCheckBox(self.page_objects_tracking)
        self.ckb_track.setChecked(True)
        self.ckb_track.setObjectName(_fromUtf8("ckb_track"))
        self.gridLayout_5.addWidget(self.ckb_track, 3, 0, 1, 1)
        self.lbl_speed_lbl = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_speed_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_speed_lbl.setObjectName(_fromUtf8("lbl_speed_lbl"))
        self.gridLayout_5.addWidget(self.lbl_speed_lbl, 4, 4, 1, 1)
        self.lbl_y_lbl = QtGui.QLabel(self.page_objects_tracking)
        self.lbl_y_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_y_lbl.setObjectName(_fromUtf8("lbl_y_lbl"))
        self.gridLayout_5.addWidget(self.lbl_y_lbl, 3, 4, 1, 1)
        self.tree_link_features = QtGui.QTreeWidget(self.page_objects_tracking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_link_features.sizePolicy().hasHeightForWidth())
        self.tree_link_features.setSizePolicy(sizePolicy)
        self.tree_link_features.setProperty("showDropIndicator", False)
        self.tree_link_features.setAlternatingRowColors(True)
        self.tree_link_features.setIndentation(0)
        self.tree_link_features.setObjectName(_fromUtf8("tree_link_features"))
        self.tree_link_features.header().setSortIndicatorShown(False)
        self.gridLayout_5.addWidget(self.tree_link_features, 5, 0, 1, 7)
        self.ckb_trace = QtGui.QCheckBox(self.page_objects_tracking)
        self.ckb_trace.setChecked(True)
        self.ckb_trace.setObjectName(_fromUtf8("ckb_trace"))
        self.gridLayout_5.addWidget(self.ckb_trace, 4, 0, 1, 1)
        self.ckb_analog_pos = QtGui.QCheckBox(self.page_objects_tracking)
        self.ckb_analog_pos.setObjectName(_fromUtf8("ckb_analog_pos"))
        self.gridLayout_5.addWidget(self.ckb_analog_pos, 2, 0, 1, 1)
        self.lbl_x = QtGui.QLabel(self.page_objects_tracking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_x.sizePolicy().hasHeightForWidth())
        self.lbl_x.setSizePolicy(sizePolicy)
        self.lbl_x.setMinimumSize(QtCore.QSize(32, 0))
        self.lbl_x.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lbl_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_x.setObjectName(_fromUtf8("lbl_x"))
        self.gridLayout_5.addWidget(self.lbl_x, 2, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 2, 1, 1, 1)
        self.dial_direction = QtGui.QDial(self.page_objects_tracking)
        self.dial_direction.setEnabled(False)
        self.dial_direction.setMaximum(359)
        self.dial_direction.setPageStep(1)
        self.dial_direction.setOrientation(QtCore.Qt.Vertical)
        self.dial_direction.setInvertedAppearance(True)
        self.dial_direction.setWrapping(True)
        self.dial_direction.setNotchTarget(20.0)
        self.dial_direction.setNotchesVisible(True)
        self.dial_direction.setObjectName(_fromUtf8("dial_direction"))
        self.gridLayout_5.addWidget(self.dial_direction, 2, 2, 3, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_objects_tracking, _fromUtf8(""))
        self.page_objects_slots = QtGui.QWidget()
        self.page_objects_slots.setGeometry(QtCore.QRect(0, 0, 239, 259))
        self.page_objects_slots.setObjectName(_fromUtf8("page_objects_slots"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_objects_slots)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.table_slots = QtGui.QTableWidget(self.page_objects_slots)
        self.table_slots.setEnabled(False)
        self.table_slots.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_slots.setAlternatingRowColors(True)
        self.table_slots.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.table_slots.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_slots.setShowGrid(True)
        self.table_slots.setObjectName(_fromUtf8("table_slots"))
        self.table_slots.setColumnCount(3)
        self.table_slots.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_slots.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_slots.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_slots.setHorizontalHeaderItem(2, item)
        self.table_slots.horizontalHeader().setMinimumSectionSize(5)
        self.table_slots.horizontalHeader().setStretchLastSection(True)
        self.table_slots.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.table_slots, 1, 0, 1, 1)
        self.btn_lock_table = QtGui.QPushButton(self.page_objects_slots)
        self.btn_lock_table.setCheckable(True)
        self.btn_lock_table.setDefault(True)
        self.btn_lock_table.setObjectName(_fromUtf8("btn_lock_table"))
        self.gridLayout_4.addWidget(self.btn_lock_table, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_objects_slots, _fromUtf8(""))
        self.page_objects_IO = QtGui.QWidget()
        self.page_objects_IO.setGeometry(QtCore.QRect(0, 0, 239, 259))
        self.page_objects_IO.setObjectName(_fromUtf8("page_objects_IO"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_objects_IO)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_8 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.page_objects_IO)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.combo_label = QtGui.QComboBox(self.page_objects_IO)
        self.combo_label.setEditable(True)
        self.combo_label.setObjectName(_fromUtf8("combo_label"))
        self.gridLayout_3.addWidget(self.combo_label, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 2, 2)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_objects_IO, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.toolBox, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(tab_objects)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(tab_objects)

    def retranslateUi(self, tab_objects):
        tab_objects.setWindowTitle(QtGui.QApplication.translate("tab_objects", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_speed.setText(QtGui.QApplication.translate("tab_objects", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_xlbl.setText(QtGui.QApplication.translate("tab_objects", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y.setText(QtGui.QApplication.translate("tab_objects", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.ckb_track.setText(QtGui.QApplication.translate("tab_objects", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_speed_lbl.setText(QtGui.QApplication.translate("tab_objects", "v:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y_lbl.setText(QtGui.QApplication.translate("tab_objects", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_link_features.headerItem().setText(0, QtGui.QApplication.translate("tab_objects", "Features", None, QtGui.QApplication.UnicodeUTF8))
        self.ckb_trace.setText(QtGui.QApplication.translate("tab_objects", "Show Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.ckb_analog_pos.setText(QtGui.QApplication.translate("tab_objects", "Analog out", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_x.setText(QtGui.QApplication.translate("tab_objects", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_tracking), QtGui.QApplication.translate("tab_objects", "Tracking", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_slots.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("tab_objects", "Property", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_slots.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("tab_objects", "Pin", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_slots.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("tab_objects", "Logic", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_lock_table.setText(QtGui.QApplication.translate("tab_objects", "Unlock", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_slots), QtGui.QApplication.translate("tab_objects", "Analog Out Slots", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("tab_objects", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("tab_objects", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("tab_objects", "Clone", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("tab_objects", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_objects_IO), QtGui.QApplication.translate("tab_objects", "In/Out", None, QtGui.QApplication.UnicodeUTF8))

