# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_featuresUi.ui'
#
# Created: Sun Jan 13 17:50:34 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_tab_features(object):
    def setupUi(self, tab_features):
        tab_features.setObjectName(_fromUtf8("tab_features"))
        tab_features.resize(319, 324)
        self.gridLayout = QtGui.QGridLayout(tab_features)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolBox = QtGui.QToolBox(tab_features)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 317, 247))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));"))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 4, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.page)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.page)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_9.addWidget(self.spinBox_5, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.page)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_9.addWidget(self.spinBox_4, 3, 2, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.page)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_9.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.page)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_9.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_9.addWidget(self.spinBox, 1, 2, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.page)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_9.addWidget(self.spinBox_6, 2, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_9.addWidget(self.pushButton_10, 4, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.combo_label = QtGui.QComboBox(self.page)
        self.combo_label.setEditable(True)
        self.combo_label.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.combo_label.setObjectName(_fromUtf8("combo_label"))
        self.combo_label.addItem(_fromUtf8(""))
        self.combo_label.addItem(_fromUtf8(""))
        self.combo_label.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.combo_label, 1, 0, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 317, 247))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.tab_features_buttons = QtGui.QWidget()
        self.tab_features_buttons.setGeometry(QtCore.QRect(0, 0, 317, 247))
        self.tab_features_buttons.setObjectName(_fromUtf8("tab_features_buttons"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_features_buttons)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_7.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_7.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_7.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_features_buttons)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_7.addWidget(self.pushButton_5, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.toolBox.addItem(self.tab_features_buttons, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(tab_features)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(tab_features)

    def retranslateUi(self, tab_features):
        tab_features.setWindowTitle(QtGui.QApplication.translate("tab_features", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("tab_features", "Tracking Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("tab_features", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("tab_features", "Sat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("tab_features", "Val", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("tab_features", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("tab_features", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setToolTip(QtGui.QApplication.translate("tab_features", "Pick thresholds from image by dragging frame around the spot of interest", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setStatusTip(QtGui.QApplication.translate("tab_features", "Pick rage from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("tab_features", "Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_label.setItemText(0, QtGui.QApplication.translate("tab_features", "redLED", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_label.setItemText(1, QtGui.QApplication.translate("tab_features", "greenLED", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_label.setItemText(2, QtGui.QApplication.translate("tab_features", "blueLED", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("tab_features", "Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), QtGui.QApplication.translate("tab_features", "Restrictions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("tab_features", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("tab_features", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("tab_features", "Clone", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("tab_features", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab_features_buttons), QtGui.QApplication.translate("tab_features", "In/Out", None, QtGui.QApplication.UnicodeUTF8))

